# Generated by Django 3.2.8 on 2023-05-24 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preparations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration_quiz',
            name='answer',
            field=models.CharField(max_length=1000),
        ),
    ]
