# Generated by Django 3.2.8 on 2023-05-25 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preparations', '0002_alter_registration_quiz_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration_quiz',
            name='option1',
        ),
        migrations.RemoveField(
            model_name='registration_quiz',
            name='option2',
        ),
        migrations.RemoveField(
            model_name='registration_quiz',
            name='option3',
        ),
        migrations.RemoveField(
            model_name='registration_quiz',
            name='option4',
        ),
        migrations.AddField(
            model_name='registration_quiz',
            name='option_a',
            field=models.CharField(default='a', max_length=255),
        ),
        migrations.AddField(
            model_name='registration_quiz',
            name='option_b',
            field=models.CharField(default='a', max_length=255),
        ),
        migrations.AddField(
            model_name='registration_quiz',
            name='option_c',
            field=models.CharField(default='a', max_length=255),
        ),
        migrations.AddField(
            model_name='registration_quiz',
            name='option_d',
            field=models.CharField(default='a', max_length=255),
        ),
        migrations.AlterField(
            model_name='registration_quiz',
            name='answer',
            field=models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D')], max_length=1),
        ),
        migrations.AlterField(
            model_name='registration_quiz',
            name='question',
            field=models.TextField(),
        ),
    ]
