# Generated by Django 3.2.8 on 2023-05-25 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preparations', '0003_auto_20230525_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration_quiz',
            name='option_a',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='registration_quiz',
            name='option_b',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='registration_quiz',
            name='option_c',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='registration_quiz',
            name='option_d',
            field=models.CharField(max_length=255),
        ),
    ]
