# Generated by Django 3.2.8 on 2023-05-25 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preparations', '0004_auto_20230525_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration_quiz',
            name='option_a',
        ),
        migrations.RemoveField(
            model_name='registration_quiz',
            name='option_b',
        ),
        migrations.RemoveField(
            model_name='registration_quiz',
            name='option_c',
        ),
        migrations.RemoveField(
            model_name='registration_quiz',
            name='option_d',
        ),
        migrations.AddField(
            model_name='registration_quiz',
            name='option1',
            field=models.CharField(default='a', max_length=1000),
        ),
        migrations.AddField(
            model_name='registration_quiz',
            name='option2',
            field=models.CharField(default='a', max_length=1000),
        ),
        migrations.AddField(
            model_name='registration_quiz',
            name='option3',
            field=models.CharField(default='a', max_length=1000),
        ),
        migrations.AddField(
            model_name='registration_quiz',
            name='option4',
            field=models.CharField(default='a', max_length=1000),
        ),
        migrations.AlterField(
            model_name='registration_quiz',
            name='answer',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='registration_quiz',
            name='question',
            field=models.CharField(default='a', max_length=1000),
        ),
    ]
