# Generated by Django 3.2.8 on 2023-05-25 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preparations', '0006_auto_20230525_1840'),
    ]

    operations = [
        migrations.CreateModel(
            name='OLQ_Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1000)),
                ('option1', models.CharField(max_length=1000)),
                ('option2', models.CharField(max_length=1000)),
                ('option3', models.CharField(max_length=1000)),
                ('option4', models.CharField(max_length=1000)),
                ('answer', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name_plural': 'OLQ_Quiz',
            },
        ),
    ]
