# Generated by Django 3.2.8 on 2023-05-29 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='domain',
            field=models.CharField(default='2021-01-01', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meeting',
            name='question',
            field=models.TextField(default='nothing'),
            preserve_default=False,
        ),
    ]
