# Generated by Django 3.2.8 on 2023-05-23 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20230523_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='bio',
            field=models.CharField(blank=True, default='Not Available', max_length=1000),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/course_pics'),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='media/mentor_pics'),
        ),
        migrations.AlterField(
            model_name='student',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='media/student_pics'),
        ),
    ]
