# Generated by Django 3.2.8 on 2023-05-25 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_mentor_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='registration_score',
            field=models.FloatField(default=0),
        ),
    ]
