# Generated by Django 3.2.8 on 2023-05-25 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_student_registration_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_registred',
            field=models.BooleanField(default=False),
        ),
    ]
