# Generated by Django 3.2.8 on 2023-05-25 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_student_is_registred'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='is_registred',
            new_name='is_registered',
        ),
    ]
