# Generated by Django 3.2.8 on 2023-05-25 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_rename_is_registred_student_is_registered'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='experties_field_of_interest',
            field=models.CharField(blank=True, choices=[('NDA', 'NDA'), ('CDS', 'CDS'), ('Territorial Army', 'Territorial Army')], max_length=100),
        ),
        migrations.AddField(
            model_name='mentor',
            name='experties_field_type',
            field=models.CharField(blank=True, choices=[('Commisioned Officer', 'Commisioned Officer'), ('Non-Commisioned Officer', 'Non-Commisioned Officer')], max_length=100),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10),
        ),
    ]
