# Generated by Django 3.2.8 on 2023-05-25 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20230525_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='experties_field_type',
            field=models.CharField(blank=True, choices=[('Commssioned Officer', 'Commssioned Officer'), ('Non-Commssioned Officer', 'Non-Commssioned Officer')], max_length=100),
        ),
    ]
