# Generated by Django 3.2.8 on 2023-05-25 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_student_is_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_mentor',
            field=models.BooleanField(default=False),
        ),
    ]
