# Generated by Django 3.2.8 on 2023-05-26 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_student_is_mentor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='is_mentor',
        ),
        migrations.RemoveField(
            model_name='student',
            name='is_student',
        ),
    ]
