# Generated by Django 3.2.8 on 2023-05-26 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20230526_0751'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('mentor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.mentor')),
            ],
            options={
                'verbose_name_plural': 'Videos',
            },
        ),
    ]
