# Generated by Django 3.2.8 on 2023-05-26 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='content',
            field=models.FileField(blank=True, upload_to='media/video_content'),
        ),
    ]
