# Generated by Django 3.2.8 on 2023-05-26 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_video_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.mentor'),
        ),
    ]
